hotfix: colon paths in changelog
webdoky/platform-next pull request #57
Opened 2024-01-22 20:26 UTC by undead404

2024-07-28 15:51 UTC, alinkedd requested changes

2024-07-28 15:51 UTC, alinkedd commented on utils/populateChangelogWithLinks.ts
> +    correctedSlug = slug.replaceAll('_doublecolon_', '::');
TODO: handle asterisk

2024-07-28 16:26 UTC, alinkedd requested changes

2024-07-28 16:26 UTC, alinkedd commented on utils/populateChangelogWithLinks.ts
> +    correctedSlug = slug.replaceAll('_doublecolon_', '::');
```suggestion
    correctedSlug = correctedSlug.replaceAll('_doublecolon_', '::');
```

2024-07-31 21:41 UTC, alinkedd commented on utils/populateChangelogWithLinks.ts
> +    correctedSlug = slug.replaceAll('_doublecolon_', '::');
я оце подумала, шо може краще chaining для чистоти? типу так
```suggestion
    const correctedSlug = slug
      .replaceAll('_colon_', ':')
      .replaceAll('_doublecolon_', '::')
      .replaceAll('_asterisk_', '*');
```

2024-08-01 06:29 UTC, undead404 commented on utils/populateChangelogWithLinks.ts
> +    correctedSlug = slug.replaceAll('_doublecolon_', '::');
Це тобі :crown:

2024-08-01 06:29 UTC, undead404 commented on utils/populateChangelogWithLinks.ts
> +      .replaceAll('_asterisk_', '*');
```suggestion
      .replaceAll('_star_', '*');
```

2024-08-01 11:46 UTC, alinkedd approved these changes
Апрув, але я тут треба ще від когось

2024-08-01 12:19 UTC, merged