Feat/algolia search
webdoky/platform-next pull request #59
Opened 2024-01-23 11:38 UTC by undead404

GitHub actions' environment variables and secrets must be set for it to be successfully deployed

2024-08-28 17:37 UTC, alinkedd requested changes
Це перша частина. Глянула все, крім самого пошуку, до нього доберусь завтра.

2024-08-28 17:37 UTC, alinkedd commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
Я можу помилятися, але env отримує наче контекст локальний
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#env-context. Тобто тут env має бути пустий, якщо не був попередньо заданий.

2024-08-28 17:37 UTC, alinkedd commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
А оці secrets для algolia вже задані в налаштуваннях репозиторію?

2024-08-28 17:37 UTC, alinkedd commented on pre-build/index.mts
> +  }
а що тепер на заміну `prepareSearchIndex()` і чому додалась обробка помилки з 
```js
    console.error(error);
    process.exit(1);
```
?

2024-08-28 17:37 UTC, alinkedd commented on tsconfig.json
> +    "transpileOnly": true
для чого знадобились ці зміни?

2024-08-28 17:37 UTC, alinkedd commented on external/original-content
А хіба треба тянути додаткові оновлення тут?

2024-08-28 17:37 UTC, alinkedd commented on components/layoutHeader.tsx
> +import Search from './search/search';
може зробити /search/index.ts для експорту і не робити тут `./search/search`? а то трохи не солідно

2024-08-28 18:22 UTC, undead404 commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
Ну він в налаштуваннях репо задається

2024-08-28 18:22 UTC, undead404 commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
Так, але їх треба перезадати

2024-08-28 18:22 UTC, undead404 commented on pre-build/index.mts
> +  }
замість prepareSearchIndex тепер окремий скрипт populate-algolia, а process.exit(1) потрібен, щоб при помилці все правильно падало

2024-08-28 18:22 UTC, undead404 commented on package.json
> +    "react-instantsearch": "~7.5.2",
Треба оновить

2024-08-28 18:22 UTC, undead404 commented on styles/globals.scss
> +  --color-ui-deprecated-border: theme("colors.red.500");
Виходить, так

2024-08-28 18:22 UTC, undead404 commented on tsconfig.json
> +    "transpileOnly": true
Лінтер зловив чомусь, не пам'ятаю вже

2024-08-28 18:22 UTC, undead404 commented on components/layoutHeader.tsx
> +import Search from './search/search';
Може!

2024-08-28 18:26 UTC, alinkedd commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
@undead404 вони задаються і йдуть у vars https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#vars-context. env лише для передачі контексту у межах самого воркфлоу/степа/джоби

2024-08-28 18:29 UTC, alinkedd commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
тобто є, наскільки я розумію, в налаштуваннях задаються саме secrets і vars

2024-08-28 18:31 UTC, alinkedd commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#example-usage-of-the-vars-context

2024-08-28 18:32 UTC, alinkedd commented on tsconfig.json
> +    "transpileOnly": true
що саме зловив? просто це не форматування, це явна зміна (для прискорення збирання?), яку краще виносити в окремий PR

2024-08-29 05:47 UTC, undead404 commented on .github/workflows/main.yml
> +          NEXT_PUBLIC_ALGOLIA_INDEX: ${{ env.ALGOLIA_INDEX }}
Згодний, виправляю

2024-08-30 06:23 UTC, closed without merging